name: Ganarate functions
on: push
jobs:
  ganarate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }}     # フォーマット
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}      # カンマで結合