name: Sequential jobs
on: push
jobs: 
  first:                                      # 依存ジョブがないので最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:                                     # firstジョブの後に実行される
    runs-on: ubuntu-latest
    needs: [first]                            # needsキーに依存するfirstジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    needs: [second]                           # needsキーに依存するsecondジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Third job"