name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is an error"     # Errorレベルのアノテーション
      - run: echo "::warning::This is an warning" # Warningレベルのアノテーション
      - run: echo "::notice::This is an notice"   # Noticeレベルのアノテーション