name: Prevent secrity misconfigurations
on: pull_request
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquasecurity/trivy-action@0.32.0 # Trivyの実行
        with:
          image-ref: config        # セキュリティ設定ミスの検出
          severity: CRITICAL,HIGH  # レポート対象の重大度
          exit-code: 1             # 問題発見時の終了ステータス